### ISSUE TITLE
cargo ndk android target = 30 ,    NETLINK_ROUTE can not success

### ISSUE THREAD

**Issue by ricoLv** [webrtc-rs/util#17]
Hi, when i compile this project for android using cargo ndk ,i set target sdk = 30 in android studio project. then the api ifaces() return fail.
according to https://developer.android.google.cn/training/articles/user-data-ids?hl=en  that article ,i downgrade the target version to 29 and it works.
but sdk target 30 or above was google play needed after 2021 .so how can i do?

**Comment by k0nserv** [comment]
We have migrated this crate to the monorepo([webrtc-rs/webrtc](https://github.com/webrtc-rs/webrtc/)) please re-open this issue over there.
