### ISSUE TITLE
hide VNet implementation behind cargo feature

### ISSUE THREAD

**Issue by chertov** [webrtc-rs/util#6]
I have a problem with mDNS package on old armv5te platforms
Armv5te doesn't support AtomicU64 and AtomicI64 types
https://doc.rust-lang.org/std/sync/atomic/#portability
this types are using in "vnet" mod.. Can we hide it behind cargo feature or change it to AtomicU32 and AtomicI32 for support this platform?
mDNS package doesn't use vnet module but has this dependency

**Comment by rainliu** [comment]
thanks for reporting this issue. Will fix this by using cargo feature for util crate.

**Comment by metaclips** [comment]
@rainliu can we use this crate instead for getting network interfaces https://docs.rs/pnet/0.8.1/pnet/index.html

**Comment by rainliu** [comment]
@chertov, I just upgrade  webrtc-util to v0.1.19  in crates.io.

You can update  mDNS crate's dependent util version to v0.1.19 in order to disable vnet feature.
